version: "3.8"

services:
  backend:
    image: jpanosso/swift-feed-backend:latest
    ports:
      - "3000:3000"
      - "2121:2121"
      - "1025-1050:1025-1050"
    depends_on:
      - mongo
    env_file:
      - backend.env
    volumes:
      - ./certs:/etc/ssl/backendcerts
    networks:
      - fullstack_network
      - mongo_network
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  frontend:
    image: jpanosso/swift-feed-frontend:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/etc/nginx/ssl
    configs:
      - source: nginx_config
        target: /etc/nginx/conf.d/default.conf
    networks:
      - fullstack_network
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  mongo:
    image: "mongo:latest"
    volumes:
      - "mongo_data:/data/db"
    networks:
      - mongo_network
    deploy:
      replicas: 1
      restart_policy:
        condition: any

networks:
  fullstack_network:
  mongo_network:

configs:
  nginx_config:
    file: ./nginx.conf

volumes:
  mongo_data:
