name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build and Push Frontend Image
        working-directory: ./frontend
        run: |
          docker build -t jpanosso/swift-feed-frontend:latest .
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker push jpanosso/swift-feed-frontend:latest

      - name: Build and Push Backend Image
        working-directory: ./backend
        run: |
          docker build -t jpanosso/swift-feed-backend:latest .
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker push jpanosso/swift-feed-backend:latest

      - name: Deploy Application
        uses: appleboy/ssh-action@v0.2.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd ${{ secrets.VPS_APP_PATH }}
            git pull
            docker-compose -f docker-compose.yml up -d
